build-info:
  script: 
    - echo "${HOSTNAME}" $(pwd) $(date)
    - curl https://hooks.slack.com/services/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 -d'{"attachments":[{"color":"#D00000","fields":[{"short":false,"title":"Notes","value":"New open task [Build completion]: \u003chttp://k8s-node-02/davidwalter0/gitlab-slack-integration/builds|Build\u003e \n"}]}]}'
  only:
    - master
  tags:
    - shell
    - ssh
