build-info:
  script: 
    - echo "${HOSTNAME}" $(pwd) $(date)
    - ls -al 
    - echo ./slack-status build-info "${?}"
    - bin/slack-status build-info "${?}"
  only:
    - master
  tags:
    - shell
    - ssh
