build-info:
  script: 
    - echo "${HOSTNAME}" $(pwd) $(date)
    - curl https://hooks.slack.com/services/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 -d"$(eval $(cat json))"
  only:
    - master
  tags:
    - shell
    - ssh
