build-info:
  script: 
    - echo "${HOSTNAME}" $(pwd) $(date)
    - curl --silent https://hooks.slack.com/services/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 -d@json
  only:
    - master
  tags:
    - shell
    - ssh
