stages:
  - build
  - deploy
  
variables:
  gitlab_user: davidwalter0
  gitlab_host: 128.107.15.214
  config_url:  http://dev-secret-config/slackurl
  secret_url:  http://dev-secret-config/kubeconfig
  deploy_yaml:    http://dev-secret-config/deploy.yaml

build-ack:
  stage: build
  script: 
    - echo "${HOSTNAME}" $(pwd) $(date)
    - ls -al 
    - echo bin/slack-status --step=gitlab-slack-integration --gitlab-host=${gitlab_host} --gitlab-user=${gitlab_user} --slack-url=${config_url} --rc=${?}
    - bin/slack-status --step=gitlab-slack-integration --gitlab-host=${gitlab_host} --gitlab-user=${gitlab_user} --slack-url=${config_url} --rc=${?}

  only:
    - master
  tags:
    - shell
    - ssh

build-env:
  stage: build
  script:
    - echo '########################################################################'
    - echo "${HOSTNAME}" $(pwd) $(date)
    - echo '########################################################################'
    - env
    - echo '########################################################################'
    - echo '########################################################################'
    - set
    - echo '########################################################################'
    - exit 0

  only:
    - master
  tags:
    - shell
    - ssh

# build-nak:
#   script: 
#     - echo "${HOSTNAME}" $(pwd) $(date)
#     - ls -al 
#     - echo ./slack-status build-info "${?}"
#     - bin/slack-status build-info "${?}"

#   only:
#     - master
#   tags:
#     - shell
#     - ssh
deploy:
  stage: deploy
  script:
    - secrets=$(mktemp)
    - yaml=$(mktemp XXXXXX.yaml)
    - |
      echo yaml=${yaml}
      echo secrets=${secrets}
      curl --silent --output ${secrets} ${secret_url}
      curl --silent --output ${yaml} ${deploy_yaml}
      if [[ -e ${secrets} ]]; then
         cat ${secrets}
         echo bin/kubectl --kubeconfig=${secrets} delete -f ${yaml}
         bin/kubectl --kubeconfig=${secrets} delete -f ${yaml} || true
         echo bin/kubectl --kubeconfig=${secrets} create -f ${yaml}
         bin/kubectl --kubeconfig=${secrets} create -f ${yaml} ; rc=${?}
         sleep 60
         bin/kubectl --kubeconfig=${secrets} get rc  falcon-api        || true
         bin/kubectl --kubeconfig=${secrets} get po  | grep falcon-api || true
         bin/kubectl --kubeconfig=${secrets} get svc falcon-api        || true
         bin/kubectl --kubeconfig=${secrets} get ep  falcon-api        || true
         rm -f ${secrets} ${yaml}
         echo "Either tunnel or add an edge node forward with a port"
         echo "ssh -nNT -L 8080:falcon-api.default.svc.cluster.local:8080 centos@k8s-master-01"
         echo "ssh -tt k8s-master-01 sudo docker run -d --restart=always --net=host k8s-master-01:5000/k8s-simple-forward:latest /k8s-simple-forward k8s-master-01:8080 falcon-api:8080"
         echo "Try url k8s-master-01 or it\'s ip \$(ping -c 1 k8s-master-01|head -2|tail -1) on port 8080"
      fi
    - bin/slack-status --step=deploy --gitlab-host=${gitlab_host} --gitlab-user=${gitlab_user} --slack-url=${config_url} --rc=${rc}
