variables:
  gitlab_user: davidwalter0
  gitlab_host: 128.107.15.214
  config_url:  http://secret-config/slackurl

build-info:
  script: 
    - echo "${HOSTNAME}" $(pwd) $(date)
    - ls -al 
    - echo ./slack-status build-info "${?}"
    - bin/slack-status build-info "${?}"
    - bin/slack-status --step=gitlab-slack-integration --gitlab-host=${gitlab_host} --gitlab-user=${gitlab_user} --slack-url=${config_url} --rc=${?}

  only:
    - master
  tags:
    - shell
    - ssh
