build-info:
  script: 
    - echo "${HOSTNAME}" $(pwd) $(date)
    # - docker info
    # - pushd deploymentapi-deploy/python_app
    # - image=falcon-app:latest
    # - master=k8s-master-01
    # - target=${master}:5000/${image}
    # - if docker build --force-rm --rm --tag ${image} . ; then docker tag -f ${image} ${target}; docker push ${target}; fi
    - |
      text=$(yaml2json --compress <<EOF
      attachments:
      - color: "#D00000"
        fallback: |
          New open task [Build completion]: <https://hooks.slack.com/services/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|Test out Slack message attachments>
        fields:
          - short: false
            title: Notes
            value: |
              build text simulation
        pretext: |
          New open task [Build Completion]: <https://hooks.slack.com/services/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|Test out Slack message attachments>

      EOF
      )
      json="$(echo ${text}|yaml2json --compress)"
      echo curl https://hooks.slack.com/services/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 -d"${json}"
      curl https://hooks.slack.com/services/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 -d"${json}"
  only:
    - master
  tags:
    - shell
    - ssh
