#!/bin/bash
dir=$(dirname $(readlink -f ${0}))
short=$(basename ${dir})
gitlabhost=k8s-node-02
user=davidwalter0
yaml2json --compress > json <<EOF
attachments:                                                                                                                                             
- color: "#D00000"
  user: GitlabWebhook
  fallback: |
     <http://${gitlabhost}/${user}/${short}/builds|${short} build complete>
  fields:                                                                                                                                                
    - short: false                                                                                                                                       
      # title: "<http://${gitlabhost}/${user}/builds|${short} build complete>"
      value: |
        <http://${gitlabhost}/${user}/${short}/builds|${short} build complete>
  # pretext: |
  #   <http://${gitlabhost}/${user}/${short}/builds|${short} build complete>
EOF

json="$(cat json)"
echo curl --silent https://hooks.slack.com/services/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 -d"'${json}'"
curl --silent https://hooks.slack.com/services/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 -d"${json}"
exit
yaml2json --compress > json <<EOF
attachments:                                                                                                                                             
- color: "#D00000"
  fallback: |
    New open task [Build completion]: <https://hooks.slack.com/services/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|Test out Slack message attachments> 
  fields:                                                                                                                                                
    - short: false                                                                                                                                       
      title: Notes                                                                                                                                       
      value: |
        build text simulation
  pretext: |
    New open task [Build Completion]: <https://hooks.slack.com/services/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|Test out Slack message attachments> 
EOF
