#!/bin/bash
yaml2json --compress > json <<EOF
attachments:                                                                                                                                             
- color: "#D00000"
  user: GitlabWebhook
  fallback: |
    <http://gitlab-slack-integration/builds|gitlab-slack-integration builds>
  fields:                                                                                                                                                
    - short: false                                                                                                                                       
      title: Build Complete
      value: |
          <http://gitlab-slack-integration/builds|gitlab-slack-integration builds>
  # pretext: |
  #   <http://gitlab-slack-integration/builds|gitlab-slack-integration builds>
EOF

json="$(cat json)"
echo curl https://hooks.slack.com/services/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 -d"'${json}'"
curl --silent https://hooks.slack.com/services/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 -d"${json}"
exit
yaml2json --compress > json <<EOF
attachments:                                                                                                                                             
- color: "#D00000"
  fallback: |
    New open task [Build completion]: <https://hooks.slack.com/services/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|Test out Slack message attachments> 
  fields:                                                                                                                                                
    - short: false                                                                                                                                       
      title: Notes                                                                                                                                       
      value: |
        build text simulation
  pretext: |
    New open task [Build Completion]: <https://hooks.slack.com/services/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|Test out Slack message attachments> 
EOF
